-- Resource Tracker — initial data (generated by scripts/rt-seed-sql.mjs from src/rt/seed.json).
-- Source: Immersive_Homes_Resource_Planner_v4.xlsx + Amin, Team US, Abhishek.
-- Run AFTER rt_schema.sql, once, in Supabase → SQL Editor. Re-running is safe: existing ids are skipped.
begin;

-- rt_disciplines: 10 rows
insert into public.rt_disciplines (id, name, kind, sort_order, active, created_at, updated_at) values
  ('b97358db-a843-5b1b-b4c0-93700c537116', 'Company Management', 'management', 0, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('0990bbd4-6569-5d5d-b68c-c0bcfae55127', 'Architecture', 'discipline', 10, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('50e84cb5-0214-55db-ade5-750b8ed69487', 'Interior Design / Kitchen / Cabinetry', 'discipline', 20, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('fa47615c-22ec-5e97-8273-d751d324a3b6', 'BIM Heroes', 'discipline', 30, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('f96609ba-b1a8-58f0-8f23-1b8bc3cbdcb0', 'Civil', 'discipline', 40, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('6dc4a6fa-7740-54e9-be29-5d55ebd9de50', 'Structural', 'discipline', 50, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('9fc4d3cd-20d4-56da-be50-3ce75c7ec81d', 'MEP', 'discipline', 60, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('ff98eb4f-4a36-528e-8083-6c61cadb510a', 'Team US', 'discipline', 70, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('325f109e-360e-5c2b-acb0-ed7ccf1523b9', 'Manufacturing', 'discipline', 80, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('a755ed1d-3a88-53dd-b397-3c14d0f7fae9', 'Project Management', 'discipline', 90, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z')
on conflict (id) do nothing;

-- rt_people: 27 rows
insert into public.rt_people (id, discipline_id, name, role, weekly_capacity_hours, sort_order, active, created_at, updated_at) values
  ('ae13eeec-cfc6-58e6-8d1c-aa085aa66eb3', '0990bbd4-6569-5d5d-b68c-c0bcfae55127', 'Mansour', 'Architecture', 40, 10, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('5e1f30ff-d207-5090-9bbf-aaa63cc147dd', '0990bbd4-6569-5d5d-b68c-c0bcfae55127', 'Hossam B', 'Architecture', 40, 20, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('46e94fb6-5b4c-5bbc-891d-d74a2ee3207e', '0990bbd4-6569-5d5d-b68c-c0bcfae55127', 'Ahmed S', 'Architecture', 40, 30, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('fb0636db-3c49-5c87-9175-cea74a63130d', '0990bbd4-6569-5d5d-b68c-c0bcfae55127', 'Ahmed M', 'Architecture', 40, 40, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('df141a8e-08c6-5833-8cd1-c778d3107414', '0990bbd4-6569-5d5d-b68c-c0bcfae55127', 'Manuel', 'Architecture', 40, 50, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('76afa9cd-9554-5b0a-b69c-946e6c2c61c1', '50e84cb5-0214-55db-ade5-750b8ed69487', 'Mai', 'Interior Design', 40, 10, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('3ffcb32c-3ba9-5732-a3a3-e7156a6fcf74', '50e84cb5-0214-55db-ade5-750b8ed69487', 'Hannah', 'Interior Design', 40, 20, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('4df2adc9-ecb7-5776-b221-435fadad965f', '50e84cb5-0214-55db-ade5-750b8ed69487', 'Lara', 'Interior Design', 40, 30, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('6da799db-0b0c-53e9-b2e2-e53d78c74092', '50e84cb5-0214-55db-ade5-750b8ed69487', 'Jocelyn', 'Cabinetry Design', 40, 40, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('b4dc45e4-dd14-5849-9a08-b0a6431cddb7', 'fa47615c-22ec-5e97-8273-d751d324a3b6', 'Mohit', 'BIM', 40, 10, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('d2e3caa1-fd59-5dd6-bea5-ff15add5bd82', 'fa47615c-22ec-5e97-8273-d751d324a3b6', 'Parvez', 'BIM', 40, 20, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('15426d66-7a53-56a2-9c93-7239cae47fe5', 'fa47615c-22ec-5e97-8273-d751d324a3b6', 'Vandana', 'BIM', 40, 30, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('fe065fa9-8097-5ac3-9ee1-19c72023137f', 'fa47615c-22ec-5e97-8273-d751d324a3b6', 'Satendra', 'BIM', 40, 40, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('a5ee7bc2-3fc7-550f-a47d-c3705fe35b07', 'fa47615c-22ec-5e97-8273-d751d324a3b6', 'Muhammed J', 'BIM', 40, 50, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('01fd2c89-da20-5ce6-84e1-4f1321bf81a6', 'f96609ba-b1a8-58f0-8f23-1b8bc3cbdcb0', 'Anees', 'Civil', 40, 10, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('63ac37dc-4eef-578b-8c06-e2462aa02dfd', 'f96609ba-b1a8-58f0-8f23-1b8bc3cbdcb0', 'Reilly', 'Civil', 40, 20, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('02a72bd7-6985-5a46-a1d1-e451197ea186', '6dc4a6fa-7740-54e9-be29-5d55ebd9de50', 'Ali', 'Structural', 40, 10, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('55f3290c-a6de-52a4-a6f7-04084977c89b', '6dc4a6fa-7740-54e9-be29-5d55ebd9de50', 'Jared', 'MWF Framing', 40, 20, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('c90d97e4-de75-5c9a-b797-06c566692f26', '9fc4d3cd-20d4-56da-be50-3ce75c7ec81d', 'Kiran', 'MEP', 40, 10, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('1ec4b1e6-d2c0-529c-906b-f258c290df0c', 'b97358db-a843-5b1b-b4c0-93700c537116', 'Amin', 'Company Manager', null, 10, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('79d561c9-4e96-5951-bc9c-a8c8605427f3', 'ff98eb4f-4a36-528e-8083-6c61cadb510a', 'Dwight', null, null, 10, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('f9bbe865-60df-5695-87cf-3cfef16b1ee3', 'ff98eb4f-4a36-528e-8083-6c61cadb510a', 'David W', null, null, 20, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('7fd2b95a-37a5-5d8e-af49-7e83c870361a', 'ff98eb4f-4a36-528e-8083-6c61cadb510a', 'JD', null, null, 30, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('74dadcfc-231d-5458-a1e4-0a938462e0f9', 'ff98eb4f-4a36-528e-8083-6c61cadb510a', 'Angel', null, null, 40, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('6d2ec41c-b052-51b1-ae30-9e45f059016a', 'ff98eb4f-4a36-528e-8083-6c61cadb510a', 'Mark Kemp', null, null, 50, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('a6426b51-356e-57fc-9a6e-80003d5773ae', 'ff98eb4f-4a36-528e-8083-6c61cadb510a', 'Karen', null, null, 60, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('8971139f-5f50-5993-8cf1-d4b6f09d0a34', 'fa47615c-22ec-5e97-8273-d751d324a3b6', 'Abhishek', null, null, 60, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z')
on conflict (id) do nothing;

-- rt_projects: 4 rows
insert into public.rt_projects (id, name, status, project_manager, start_date, target_finish, notes, active, created_at, updated_at) values
  ('12179f4b-bd46-5df3-8eba-6a866f77f405', 'Reeds lake', 'Active', null, '2026-10-05', '2026-12-18', 'Replace with real project names.', true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('208987da-12e4-59ab-a690-a0f8270ce8df', 'Cushman', null, null, null, null, null, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('57e401e3-6d87-5a4a-90a5-6f440f687f22', 'Milner', null, null, null, null, null, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('946cca06-360c-5c82-a48f-0396e8fef8f8', 'Morgan', null, null, null, null, null, true, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z')
on conflict (id) do nothing;

-- rt_tasks: 46 rows
insert into public.rt_tasks (id, person_id, project_id, title, phase_key, start_date, due_date, hours_per_week, status, priority, notes, sort_order, active, source_row, created_at, updated_at) values
  ('8b597762-5a45-5840-a469-d9d0cbd49558', 'ae13eeec-cfc6-58e6-8d1c-aa085aa66eb3', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Radiant floor detail and nested Revit family', null, null, null, null, 'Waiting', 'High', 'Waiting on JD’s radiant parts list', 80, true, 8, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('dd96bf8a-94a3-52a1-ac00-3b7be7f9ba77', '76afa9cd-9554-5b0a-b69c-946e6c2c61c1', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Full Design Lock', null, '2026-10-05', '2026-10-07', null, 'In Progress', 'Critical', 'Selctions Materials , Appliances, Everything , Revit Families,', 760, true, 76, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('fe067155-e80d-56fd-b115-4a98cfd15dcf', '76afa9cd-9554-5b0a-b69c-946e6c2c61c1', '208987da-12e4-59ab-a690-a0f8270ce8df', 'Full Design Lock', null, '2026-10-08', '2026-10-15', null, 'In Progress', 'High', null, 770, true, 77, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('52144d5f-7067-5cb0-9c68-78eae45f9464', '76afa9cd-9554-5b0a-b69c-946e6c2c61c1', '12179f4b-bd46-5df3-8eba-6a866f77f405', 'Full Design Lock', null, null, '2026-10-19', null, 'In Progress', 'High', null, 780, true, 78, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('e8fd042e-5ce4-5a7c-bf51-98c23839f9b9', '76afa9cd-9554-5b0a-b69c-946e6c2c61c1', '57e401e3-6d87-5a4a-90a5-6f440f687f22', 'Client Selection Process', null, null, '2026-10-30', null, 'Waiting', 'High', 'Material Selection, Kitchen Layout, Cabinetry', 790, true, 79, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('c6e13ff0-2f4c-5df1-8499-baba5dd8ffd3', '76afa9cd-9554-5b0a-b69c-946e6c2c61c1', '57e401e3-6d87-5a4a-90a5-6f440f687f22', 'Full Design Lock', null, null, '2026-11-20', null, 'Waiting', 'Medium', null, 800, true, 80, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('db0cffcb-ea42-55e3-8492-d7cb2ccdb533', 'b4dc45e4-dd14-5849-9a08-b0a6431cddb7', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Incorporate David W''s redlines', null, null, null, null, null, null, 'Joint with Parvez', 1350, true, 135, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('df1a38ac-4c14-5be2-ba69-ffdad53a37b5', 'b4dc45e4-dd14-5849-9a08-b0a6431cddb7', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Add consolidated redline set items', null, null, null, null, null, null, 'Joint with Parvez; waiting on consolidated redline set', 1360, true, 136, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('5f09f25c-44de-573e-b0f7-36b5d109878b', 'b4dc45e4-dd14-5849-9a08-b0a6431cddb7', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Elevation and detail changes for new floor height', null, null, null, null, null, null, 'Joint with Parvez; waiting on floor-height confirmation', 1370, true, 137, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('526e5fe4-daf1-5be6-bad1-44376473debb', 'b4dc45e4-dd14-5849-9a08-b0a6431cddb7', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Primary bath option in separate Revit file', null, null, null, null, null, null, 'Joint with Parvez', 1380, true, 138, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('266f1c31-7ecf-5ae8-bab8-3ac655897284', 'b4dc45e4-dd14-5849-9a08-b0a6431cddb7', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Move primary bath option into ACC model', null, null, null, null, null, null, 'Joint with Parvez; after client approval/change order', 1390, true, 139, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('bcb681ff-3750-5a1c-a680-26c28eda0739', 'b4dc45e4-dd14-5849-9a08-b0a6431cddb7', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Update insulation callouts', null, null, null, null, null, null, 'Joint with Parvez', 1400, true, 140, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('d2f6faa3-e9a8-56f0-a608-6708c4882771', 'b4dc45e4-dd14-5849-9a08-b0a6431cddb7', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Locate radiant underfloor detail and add it to the set', null, null, null, null, null, null, 'Joint with Kiran and Parvez', 1410, true, 141, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('20be62c7-be85-5fec-aa93-41dd3e393bd0', 'd2e3caa1-fd59-5dd6-bea5-ff15add5bd82', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Incorporate David W''s redlines', null, null, null, null, null, null, 'Joint with Mohit', 1440, true, 144, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('ca9a7bc3-5219-5501-bdf2-0fb12df1b739', 'd2e3caa1-fd59-5dd6-bea5-ff15add5bd82', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Add consolidated redline set items', null, null, null, null, null, null, 'Joint with Mohit; waiting on consolidated redline set', 1450, true, 145, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('a84183ac-6119-55e2-970c-50f453371ff4', 'd2e3caa1-fd59-5dd6-bea5-ff15add5bd82', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Elevation and detail changes for new floor height', null, null, null, null, null, null, 'Joint with Mohit; waiting on floor-height confirmation', 1460, true, 146, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('78933bb5-bd0f-5599-95a4-25afe2bf7b9c', 'd2e3caa1-fd59-5dd6-bea5-ff15add5bd82', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Primary bath option in separate Revit file', null, null, null, null, null, null, 'Joint with Mohit', 1470, true, 147, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('095e2447-c284-521d-8d15-f3a5778b6b01', 'd2e3caa1-fd59-5dd6-bea5-ff15add5bd82', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Move primary bath option into ACC model', null, null, null, null, null, null, 'Joint with Mohit; after client approval/change order', 1480, true, 148, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('92baaf8a-ddf0-5ac7-a75f-a22aedb0b8d8', 'd2e3caa1-fd59-5dd6-bea5-ff15add5bd82', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'MEP room updates', null, null, null, null, null, null, null, 1490, true, 149, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('3e4fd72e-2930-56ab-9e04-77843d885f38', 'd2e3caa1-fd59-5dd6-bea5-ff15add5bd82', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Update insulation callouts', null, null, null, null, null, null, 'Joint with Mohit', 1500, true, 150, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('fe9b0999-269d-5d8f-94d3-9eb570937790', 'd2e3caa1-fd59-5dd6-bea5-ff15add5bd82', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Garage and basement lights to 6" round Maxima, 1250 lm', null, null, null, null, null, null, 'Spec question still open; basement ceiling type to align', 1510, true, 151, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('45f3c44b-714e-5f01-a91e-9e5d30122858', 'd2e3caa1-fd59-5dd6-bea5-ff15add5bd82', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Put ship-loose item list on factory/site sheet', null, null, null, null, null, null, 'Waiting on preliminary ship-loose list', 1520, true, 152, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('b794627b-e1b1-5ab4-826c-2d60a96497cf', 'd2e3caa1-fd59-5dd6-bea5-ff15add5bd82', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Add door schedule data', null, null, null, null, null, null, 'Waiting on door schedule information', 1530, true, 153, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('b90342a2-71c2-5bf7-b8ef-8247d64e9144', 'd2e3caa1-fd59-5dd6-bea5-ff15add5bd82', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Locate radiant underfloor detail and add it to the set', null, null, null, null, null, null, 'Joint with Kiran and Mohit', 1540, true, 154, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('c3ff410f-70db-5673-988e-2f655c3dfbc5', 'fe065fa9-8097-5ac3-9ee1-19c72023137f', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Steel takeoff to validate cost reduction', null, null, null, null, null, null, 'Coordinating with Dwight and JD', 1660, true, 166, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('2e83c3a9-fb8a-562e-a25f-22283e3d6127', '01fd2c89-da20-5ce6-84e1-4f1321bf81a6', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Site plan Sheet', null, null, '2026-10-06', null, 'In Progress', 'Critical', null, 2070, true, 207, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('2bb0ff4a-a4f8-5d0d-845c-852051cabb9c', '01fd2c89-da20-5ce6-84e1-4f1321bf81a6', '208987da-12e4-59ab-a690-a0f8270ce8df', 'Site plan Sheet', null, '2026-10-08', '2026-10-15', null, 'In Progress', 'Critical', null, 2080, true, 208, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('f27f21be-b872-5a54-a9b8-2f4d4d226008', '01fd2c89-da20-5ce6-84e1-4f1321bf81a6', '12179f4b-bd46-5df3-8eba-6a866f77f405', 'Posting Site plan Sheet', null, null, '2026-10-05', null, 'Waiting', 'High', null, 2090, true, 209, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('20233a6e-9684-53c8-abd0-8fa93177c796', '01fd2c89-da20-5ce6-84e1-4f1321bf81a6', '57e401e3-6d87-5a4a-90a5-6f440f687f22', 'Site plan Sheet', null, '2026-10-15', '2026-10-29', null, 'Not Started', 'High', null, 2100, true, 210, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('779c0079-bc42-5c5d-bdc7-226d2465ee52', '63ac37dc-4eef-578b-8c06-e2462aa02dfd', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Floor system and sanitary drain/vent runs in rotated 14" truss floor; return to Kiran', null, null, null, null, null, null, 'Joint with Jared; Dwight stated a midday 10/7 target', 2160, true, 216, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('e1d5cf1f-17ac-5717-b659-d16bff1f4160', '63ac37dc-4eef-578b-8c06-e2462aa02dfd', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'HOA height check for ~2" increase', null, null, null, null, null, null, 'Municipal height already confirmed', 2170, true, 217, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('27dc06cc-0997-58ec-9fde-0272ca4ce1db', '02a72bd7-6985-5a46-a1d1-e451197ea186', '12179f4b-bd46-5df3-8eba-6a866f77f405', 'Concrete Work', null, null, null, null, null, 'Critical', null, 2480, true, 248, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('e31a06c8-b969-58dd-a955-24f819371a45', '55f3290c-a6de-52a4-a6f7-04084977c89b', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Floor system and sanitary drain/vent runs in rotated 14" truss floor; return to Kiran', null, null, null, null, null, null, 'Joint with Reilly; Dwight stated a midday 10/7 target', 2570, true, 257, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('40ed5ff3-4fea-5a4b-8a14-0c110a3a05dd', 'c90d97e4-de75-5c9a-b797-06c566692f26', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'MEP BSAR Sets', null, null, '2026-10-09', null, 'In Progress', 'Critical', 'Blocker Radiant floor Heating', 2890, true, 289, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('40fca706-5adb-543f-bb59-02535da8ac29', 'c90d97e4-de75-5c9a-b797-06c566692f26', '208987da-12e4-59ab-a690-a0f8270ce8df', 'MEP BSAR Sets', null, '2026-10-15', '2026-11-05', null, 'Blocked', 'High', 'Waiting Architecture Freeze', 2900, true, 290, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('c2ae4fc1-91e8-5083-b07a-74e52d574dd2', 'c90d97e4-de75-5c9a-b797-06c566692f26', '12179f4b-bd46-5df3-8eba-6a866f77f405', 'Clash Detection', null, '2026-10-10', '2026-10-15', null, 'In Progress', 'Critical', null, 2910, true, 291, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('18cd0543-4d49-5033-838d-2e71e727dab1', 'c90d97e4-de75-5c9a-b797-06c566692f26', '12179f4b-bd46-5df3-8eba-6a866f77f405', 'MEP BSAR Sets', null, '2026-11-05', '2026-11-26', null, 'Blocked', 'High', 'Waiting Architecture Freeze', 2920, true, 292, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('31ae4ed9-c68f-5bd0-a5f5-e220ebf0832e', 'c90d97e4-de75-5c9a-b797-06c566692f26', '57e401e3-6d87-5a4a-90a5-6f440f687f22', 'MEP BSAR Sets', null, '2026-11-26', '2026-12-10', null, 'Blocked', 'High', 'Waiting Architecture Freeze', 2930, true, 293, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('f4a80794-68e1-5502-a016-85b70d97d6d8', 'c90d97e4-de75-5c9a-b797-06c566692f26', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Locate radiant underfloor detail and add it to the set', null, null, null, null, null, null, 'Joint with Mohit and Parvez', 2940, true, 294, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('6fb369db-cd42-5615-b0f3-63507e69845e', 'c90d97e4-de75-5c9a-b797-06c566692f26', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Reconnect ducting to relocated fan coils, ERV and makeup air in catwalk zone', null, null, null, null, null, null, null, 2950, true, 295, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('e0aa998d-97c3-5881-a42c-92a2425eefd4', 'c90d97e4-de75-5c9a-b797-06c566692f26', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Raise any issue with attic equipment placement', null, null, null, null, null, null, null, 2960, true, 296, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('adaa10ad-1baf-5c66-8b70-a7e3f9c43ea3', 'c90d97e4-de75-5c9a-b797-06c566692f26', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Confirm fan coils have internal condensate containment', null, null, null, null, null, null, null, 2970, true, 297, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('f753a1ae-5d15-5f4e-8375-c5cec5f7ed14', 'c90d97e4-de75-5c9a-b797-06c566692f26', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Publish electrical PDF to ACC', null, null, null, null, null, null, null, 2980, true, 298, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('9a215e87-5129-5d9b-99a0-cd953ea087ed', 'c90d97e4-de75-5c9a-b797-06c566692f26', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Add receptacles/power for sump pump, radon fan and well pump in MEP room', null, null, null, null, null, null, null, 2990, true, 299, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('dfaf7324-26a3-597e-970d-b77f9b5becb1', 'c90d97e4-de75-5c9a-b797-06c566692f26', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Check fixture runs and risers on US team’s drain/vent runs', null, null, null, null, null, null, 'Waiting on US drain/vent runs', 3000, true, 300, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z'),
  ('45f63e4c-a766-520e-bb9b-08e06cc67719', 'c90d97e4-de75-5c9a-b797-06c566692f26', '946cca06-360c-5c82-a48f-0396e8fef8f8', 'Transfer grille callout', null, null, null, null, null, null, 'Waiting on design-team grille decision', 3010, true, 301, '2026-10-08T00:00:00Z', '2026-10-08T00:00:00Z')
on conflict (id) do nothing;

commit;
