// PM Workflow phase reference — READ-ONLY SNAPSHOT of the six permanent phase ids and current names
// from the PM Workflow template (generated by the internal repo's scripts/make-tracker-repo.mjs).
// Resource Tracker tasks store only the permanent id (rt_tasks.phase_key). Ids never change; names are display only.
// The PM Workflow itself is not part of this repository and no data is shared with it.
export const PM_PHASES = [
  {
    "key": "phase-conceptual-design-contract",
    "no": "01",
    "label": "Conceptual Design & Contract Signing"
  },
  {
    "key": "phase-design-development-freeze",
    "no": "02",
    "label": "Design Development & Design Freeze"
  },
  {
    "key": "phase-coordinated-design",
    "no": "03",
    "label": "Coordinated Design"
  },
  {
    "key": "phase-permit-documentation",
    "no": "04",
    "label": "Permit Documentation"
  },
  {
    "key": "phase-construction-docs-manufacturing-readiness",
    "no": "05",
    "label": "Construction Documents & Manufacturing Readiness"
  },
  {
    "key": "phase-site-manufacturing-construction",
    "no": "06",
    "label": "Site Work, Manufacturing & Construction"
  }
];
export const phaseByKey = Object.fromEntries(PM_PHASES.map((p) => [p.key, p]));
export const phaseLabel = (key) => { const p = phaseByKey[key]; return p ? `${p.no} ${p.label}` : 'Not assigned'; };
export const LEGACY_PHASE_KEYS = Object.fromEntries(PM_PHASES.map((p, i) => [`PH${i + 1}`, p.key]));
